src/Entity/Adherant.php
<?php

namespace App\Entity;

use App\Repository\AdherantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdherantRepository::class)
 */
class Adherant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_soinclair;

    /**
    * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cartesoinclair;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $cin;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="adherants",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_client;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_conjoint_first;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_conjoint_second;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbr_enfant;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $situation_pro;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $category_sociopro;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $maladie_chroni;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $formule_soin_clair;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $supp_one;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $supp_two;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $supp_three;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phonenumber;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $subscription_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $expiring_date;

    /**
     * @ORM\OneToMany(targetEntity=Demande::class, mappedBy="adherent", orphanRemoval=true)
     */
    private $demandes;

    public function __construct()
    {
        $this->demandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCartesoinclair(): ?string {
        return $this->cartesoinclair;
    }

    public function setCartesoinclair(string $cartesoinclair): self{
        $this->cartesoinclair = $cartesoinclair;
        return $this;
    }

    public function getNumeroSoinclair(): ?string
    {
        return $this->numero_soinclair;
    }

    public function setNumeroSoinclair(string $numero_soinclair): self
    {
        $this->numero_soinclair = $numero_soinclair;

        return $this;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(string $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(?string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getCodeClient(): ?string
    {
        return $this->code_client;
    }

    public function setCodeClient(?string $code_client): self
    {
        $this->code_client = $code_client;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getNomConjointFirst(): ?string
    {
        return $this->nom_conjoint_first;
    }

    public function setNomConjointFirst(?string $nom_conjoint_first): self
    {
        $this->nom_conjoint_first = $nom_conjoint_first;

        return $this;
    }

    public function getNomConjointSecond(): ?string
    {
        return $this->nom_conjoint_second;
    }

    public function setNomConjointSecond(?string $nom_conjoint_second): self
    {
        $this->nom_conjoint_second = $nom_conjoint_second;

        return $this;
    }

    public function getNbrEnfant(): ?int
    {
        return $this->nbr_enfant;
    }

    public function setNbrEnfant(?int $nbr_enfant): self
    {
        $this->nbr_enfant = $nbr_enfant;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getSituationPro(): ?string
    {
        return $this->situation_pro;
    }

    public function setSituationPro(string $situation_pro): self
    {
        $this->situation_pro = $situation_pro;

        return $this;
    }

    public function getCategorySociopro(): ?string
    {
        return $this->category_sociopro;
    }

    public function setCategorySociopro(?string $category_sociopro): self
    {
        $this->category_sociopro = $category_sociopro;

        return $this;
    }

    public function getMaladieChroni(): ?string
    {
        return $this->maladie_chroni;
    }

    public function setMaladieChroni(?string $maladie_chroni): self
    {
        $this->maladie_chroni = $maladie_chroni;

        return $this;
    }

    public function getFormuleSoinClair(): ?string
    {
        return $this->formule_soin_clair;
    }

    public function setFormuleSoinClair(?string $formule_soin_clair): self
    {
        $this->formule_soin_clair = $formule_soin_clair;

        return $this;
    }

    public function getSuppOne(): ?string
    {
        return $this->supp_one;
    }

    public function setSuppOne(?string $supp_one): self
    {
        $this->supp_one = $supp_one;

        return $this;
    }

    public function getSuppTwo(): ?string
    {
        return $this->supp_two;
    }

    public function setSuppTwo(?string $supp_two): self
    {
        $this->supp_two = $supp_two;

        return $this;
    }

    public function getSuppThree(): ?string
    {
        return $this->supp_three;
    }

    public function setSuppThree(?string $supp_three): self
    {
        $this->supp_three = $supp_three;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPhonenumber(): ?string
    {
        return $this->phonenumber;
    }

    public function setPhonenumber(?string $phonenumber): self
    {
        $this->phonenumber = $phonenumber;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getSubscriptionDate(): ?\DateTimeInterface
    {
        return $this->subscription_date;
    }

    public function setSubscriptionDate(?\DateTimeInterface $subscription_date): self
    {
        $this->subscription_date = $subscription_date;

        return $this;
    }

    public function getExpiringDate(): ?\DateTimeInterface
    {
        return $this->expiring_date;
    }

    public function setExpiringDate(?\DateTimeInterface $expiring_date): self
    {
        $this->expiring_date = $expiring_date;

        return $this;
    }

    /**
     * @return Collection|Demande[]
     */
    public function getDemandes(): Collection
    {
        return $this->demandes;
    }

    public function addDemande(Demande $demande): self
    {
        if (!$this->demandes->contains($demande)) {
            $this->demandes[] = $demande;
            $demande->setAdherent($this);
        }

        return $this;
    }

    public function removeDemande(Demande $demande): self
    {
        if ($this->demandes->removeElement($demande)) {
            // set the owning side to null (unless already changed)
            if ($demande->getAdherent() === $this) {
                $demande->setAdherent(null);
            }
        }

        return $this;
    }
}

src/Form/AdherantType.php
<?php

namespace App\Form;

use App\Entity\Adherant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class AdherantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numero_soinclair', TextType::class)
            ->add('cin', TextType::class)
            ->add('cartesoinclair', FileType::class, [
                'label' => 'Carte SoinClair (image file)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF document',
                    ])
                ],
            ])
            ->add('entreprise')
            ->add('code_client')
            ->add('phonenumber',TelType::class)
            ->add('lastname')
            ->add('firstname')
            ->add('ville')
            ->add('nom_conjoint_first')
            ->add('nom_conjoint_second')
            ->add('nbr_enfant')
            ->add('adresse')
            ->add('situation_pro',ChoiceType::class,[
                'choices'=>[
                    'actif' => 'actif',
                    'retraité' => 'retraité',
                    'Activité libérale' => 'Activité libérale',
                ]
            ])
            ->add('category_sociopro',ChoiceType::class,[
                'choices'=>[
                    'actif' => 'actif',
                    ' ' => ' ',
                ]
            ])
            ->add('maladie_chroni',ChoiceType::class,[
                'choices'=>[
                    'diabèthe' => 'diabèthe',
                    ' ' => ' ',
                ]
            ])
            ->add('formule_soin_clair',ChoiceType::class,[
                'choices'=>[
                    'premium' => 'premium',
                    'standard' => 'standard',
                    'classique' => 'classique',
                    ' ' => ' ',
                ]
            ])
            ->add('supp_one')
            ->add('supp_two')
            ->add('supp_three')
            ->add('user',UserType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Adherant::class,
        ]);
    }
}

templates/adherant/_delete_form.html.twig
<form method="post" action="{{ path('adherant_delete', {'id': adherant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adherant.id) }}">
    <button class="btn btn-danger btn-default">Delete</button>
</form>

templates/adherant/edit.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Adherant - edit{% endblock %}

{% block content %}
<div class="x_panel">
    <div class="x_content">

        <a href="{{ path('adherant_index') }}" class="btn btn-app">
            <i class="fa fa-list"></i> List
        </a>

        <a href="{{ path('adherant_new') }}" class="btn btn-app">
                <i class="fa fa-save"></i> Nouveau
        </a>

        <a href="{{ path('adherant_import') }}" class="btn btn-app">
            <i class="fa fa-database"></i> import
            <small>Adhérents</small>
        </a>


        <a href="{{ path('adherant_importzip') }}"  class="btn btn-app">
            <i class="fa fa-credit-card"></i> import
            <small>Cartes</small>
        </a>


        {{ include('adherant/_delete_form.html.twig') }}

    </div>
</div>

<div class="x_panel">
    <div class="x_title">
        <h2>Modification d'Adhérent</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">

    {{ include('adherant/_form.html.twig', {'button_label': 'Update'}) }}
    </div>
</div>

{% endblock %}

templates/adherant/import.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Adherant index{% endblock %}
{% block title_page_admin %}Espace adhérent <small>accès administrateur</small>{% endblock %}

{% block content %}
<div class="x_panel">
    <div class="x_content">

        <a href="{{ path('adherant_index') }}" class="btn btn-app">
            <i class="fa fa-list"></i> List
        </a>

        <a href="{{ path('adherant_new') }}" class="btn btn-app">
            <i class="fa fa-save"></i> Nouveaus
        </a>

        <a href="{{ path('adherant_import') }}" class="btn btn-app">
            <i class="fa fa-database"></i> import
        </a>

        <a href="{{ path('adherant_importzip') }}"  class="btn btn-app">
            <i class="fa fa-credit-card"></i> import
            <small>Cartes</small>
        </a>

    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Import des adhérents</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <p>
            Charger le fichier contenant les adhérents en respectant le format du fichier suivant : <br/>
                <a href="{{ asset('uploads/Template/Template_import.xlsx') }}">
                    <i class="fa fa-download"></i>Modèle
                </a>
            <br>
        </p>
        <form  action="{{ path('upload-excel') }}" method="POST"  enctype="multipart/form-data">
            <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align">Fichier d'upload</label>
                <input type="file" name="myfile" class="" />
            </div>

            <div class="ln_solid"></div>
            <div class="item form-group">
                <div class="col-md-6 col-sm-6 offset-md-3">
                    <button class="btn btn-primary" type="reset">Reset</button>
                    <input class="btn btn-success" type="submit" value="submit"/>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/adherant/import_card.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Adherant index{% endblock %}
{% block title_page_admin %}Espace adhérent <small>accès administrateur</small>{% endblock %}

{% block content %}
    <div class="x_panel">
        <div class="x_content">

            <a href="{{ path('adherant_index') }}" class="btn btn-app">
                <i class="fa fa-list"></i> List
            </a>

            <a href="{{ path('adherant_new') }}" class="btn btn-app">
                <i class="fa fa-save"></i> Nouveaus
            </a>

            <a href="{{ path('adherant_import') }}" class="btn btn-app">
                <i class="fa fa-database"></i> import
            </a>

            <a href="{{ path('adherant_importzip') }}"  class="btn btn-app">
                <i class="fa fa-credit-card"></i> import
                <small>Cartes</small>
            </a>

        </div>
    </div>
    <div class="x_panel">
        <div class="x_title">
            <h2>Import des cartes Soin Clair</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <p>
                Charger un fichier d'extension (.ZIP) contenant les fichiers renommé avec le numéro soin clair de l'adhérent<br/>

                <br>
            </p>
            <form  action="{{ path('upload-zip') }}" method="POST"  enctype="multipart/form-data">
                <div class="item form-group">
                    <label class="col-form-label col-md-3 col-sm-3 label-align">Fichier d'upload</label>
                    <input type="file" name="myfile" class="" />
                </div>

                <div class="ln_solid"></div>
                <div class="item form-group">
                    <div class="col-md-6 col-sm-6 offset-md-3">
                        <button class="btn btn-primary" type="reset">Reset</button>
                        <input class="btn btn-success" type="submit" value="submit"/>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/adherant/index.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Adherant index{% endblock %}
{% block title_page_admin %}Espace adhérent accès administrateur{% endblock %}


{% block content %}
<div class="x_panel">
    <div class="x_title">
        <h2>   Actions
        </h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>

    <div class="x_content">
        <a href="{{ path('adherant_new') }}"  class="btn btn-app">
            <i class="fa fa-save"></i> Nouveau
        </a>

        <a href="{{ path('adherant_import') }}"  class="btn btn-app">
            <i class="fa fa-database"></i> import
            <small>Adhérents</small>
        </a>


        <a href="{{ path('adherant_importzip') }}"  class="btn btn-app">
            <i class="fa fa-credit-card"></i> import
            <small>Cartes</small>
        </a>

    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Liste des adhérents</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <div class="card-box table-responsive">
            <p class="text-muted font-13 m-b-30">
                <br/>
            </p>

                <table id="datatable_adherant" class="table table-striped table-bordered dataTable no-footer">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>N° Soin Clair</th>
                            <th>Cin</th>
                            <th>Nom & Prénom</th>
                            <th>Code Client</th>
                            <th>Entreprise</th>
                            <th>actions</th>
                        </tr>

                    </thead>
                    <tbody>
                        {% for adherant in adherants %}
                            <tr>
                                <td>{{ adherant.id }}</td>
                                <td>{{ adherant.numeroSoinclair }}</td>
                                <td>{{ adherant.cin }}</td>
                                <td>{{ adherant.lastname ~ ' ' ~ adherant.firstname }}</td>
                                <td>{{ adherant.codeclient }}</td>
                                <td>{{ adherant.entreprise }}</td>
                                <td>
                                    <a href="{{ path('adherant_show', {'id': adherant.id}) }}"  class="btn btn-default">
                                        <i class="fa fa-eye"></i> show
                                    </a>
                                    <a href="{{ path('adherant_edit', {'id': adherant.id}) }}"  class="btn btn-default">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="4">no records found</td>
                            </tr>
                        {% endfor %}
                    </tbody>

                </table>

        </div>
    </div>
</div>

{% endblock %}

{% block extra_script_admin %}
{% endblock %}

templates/adherant/new.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}New Adherant{% endblock %}
{% block title_page_admin %}Espace adhérent accès administrateur{% endblock %}

{% block content %}
    <div class="x_panel">
        <div class="x_content">

            <a href="{{ path('adherant_index') }}" class="btn btn-app">
                <i class="fa fa-list"></i> List
            </a>

            <a href="{{ path('adherant_new') }}" class="btn btn-app">
                <i class="fa fa-save"></i> Nouveaus
            </a>

            <a href="{{ path('adherant_import') }}" class="btn btn-app">
                <i class="fa fa-database"></i> import
                <small>Adhérents</small>
            </a>

            <a href="{{ path('adherant_importzip') }}"  class="btn btn-app">
                <i class="fa fa-credit-card"></i> import
                <small>Cartes</small>
            </a>

        </div>
    </div>
    <div class="x_panel">
        <div class="x_title">
            <h2>Enregistrement Adhérent</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

            {{ include('adherant/_form.html.twig') }}

        </div>
    </div>


{% endblock %}

templates/adherant/show.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Adhérent {% endblock %}
{% block title_page_admin %}Espace adhérent <small>accès administrateur</small>{% endblock %}

{% block content %}
    <div class="x_panel">
        <div class="x_content">

            <a href="{{ path('adherant_index') }}" class="btn btn-app">
                <i class="fa fa-list"></i> List
            </a>

            <a href="{{ path('adherant_new') }}" class="btn btn-app">
                <i class="fa fa-save"></i> Nouveaus
            </a>

            <a href="{{ path('adherant_import') }}" class="btn btn-app">
                <i class="fa fa-database"></i> import
                <small>Adhérents</small>
            </a>

            <a href="{{ path('adherant_importzip') }}"  class="btn btn-app">
                <i class="fa fa-credit-card"></i> import
                <small>Cartes</small>
            </a>

            <a href="{{ path('adherant_edit', {'id': adherant.id}) }}" class="btn btn-app">
                <i class="fa fa-edit"></i> Edit
            </a>


            {{ include('adherant/_delete_form.html.twig') }}

        </div>
    </div>

<div class="x_panel">
    <div class="x_title">
        <h2>Profil Adhérent -<small>{{ adherant.numeroSoinclair }}</small></h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <div class="col-md-3 col-sm-3  profile_left">

            <div class="profile_img">
                <div id="crop-avatar">
                    {% if adherant.cartesoinclair is not empty %}
                        <img class="img-responsive avatar-view" src="{{ asset('uploads/cartesoinclair/' ~ adherant.cartesoinclair) }}" alt="Avatar" title="Change the avatar">
                    {% else %}
                        <img class="img-responsive avatar-view" src="{{ asset('/admin/production/images/inbox.png') }}" alt="Avatar" title="Change the avatar">

                    {% endif %}
                </div>
            </div>
            <h3>{{ adherant.user.username }}</h3>
            <ul class="list-unstyled user_data">
                <li><i class="fa fa-map-marker user-profile-icon"></i> {{ adherant.adresse }},{{ adherant.ville }}, USA
                </li>
                <li>
                    <i class="fa fa-briefcase user-profile-icon"></i> {{ adherant.situationpro }}
                </li>
                <li>
                    <i class="fa fa-briefcase user-profile-icon"></i> {{ adherant.categorysociopro }}
                </li>

                <li class="m-top-xs">
                    <i class="fa fa-external-link user-profile-icon"></i>
                    <a href="#" >{{ adherant.numeroSoinclair }}</a>
                </li>
            </ul>
            <a href="{{ path('adherant_edit', {'id': adherant.id}) }}" class="btn btn-success"><i class="fa fa-edit m-right-xs"></i>Edit Profile</a>
        </div>
        <div class="col-md-9 col-sm-9 ">
            <table class="table">
                <tbody>
                <tr>
                    <th>Entreprise</th>
                    <td>{{ adherant.entreprise }}</td>
                </tr>
                <tr>
                    <th>Code Client</th>
                    <td>{{ adherant.codeclient }}</td>
                </tr>
                <tr>
                    <th>Date d'inscription</th>
                    <td>{{ adherant.subscriptiondate | date }}</td>
                </tr>
                <tr>
                    <th>Date d'éxpiration</th>
                    <td>{{ adherant.expiringdate | date }}</td>
                </tr>
                <tr>
                    <th>Nom & prénom</th>
                    <td>{{ adherant.firstname ~ ' ' ~ adherant.lastname }}</td>
                </tr>
                <tr>
                    <th>Nom conjoint 1</th>
                    <td>{{ adherant.nomconjointfirst }}</td>
                </tr>
                <tr>
                    <th>Nom conjoint 2</th>
                    <td>{{ adherant.nomconjointsecond }}</td>
                </tr>
                <tr>
                    <th>Nombre d'enfant</th>
                    <td>{{ adherant.nbrenfant }}</td>
                </tr>

                <tr>
                    <th>Date de naissance</th>
                    <td>{{ adherant.datenaissance | date }}</td>
                </tr>
                <tr>
                    <th>N° mobile</th>
                    <td>{{ adherant.phonenumber }}</td>
                </tr>


                <tr>
                    <th>N° Cin</th>
                    <td>{{ adherant.cin }}</td>
                </tr>

                </tbody>
            </table>
            <div class="profile_title">
                <div class="col-md-6">
                    <h2>User Activity Report</h2>
                </div>
                <div class="col-md-6">
                    <div id="reportrange" class="pull-right" style="margin-top: 5px; background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #E6E9ED">
                        <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                        <span>March 27, 2021 - April 25, 2021</span> <b class="caret"></b>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}