src/Entity/Partenaire.php
<?php

namespace App\Entity;

use App\Repository\PartenaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PartenaireRepository::class)
 */
class Partenaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo_path;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $specialite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="text")
     */
    private $description_profil;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $tarifs;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="partenaires",cascade={"persist"}).
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tarifs_path;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $champs_supp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $horraires;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_fix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_mobile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logo_path;
    }

    public function setLogoPath(?string $logo_path): self
    {
        $this->logo_path = $logo_path;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(?string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(string $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDescriptionProfil(): ?string
    {
        return $this->description_profil;
    }

    public function setDescriptionProfil(string $description_profil): self
    {
        $this->description_profil = $description_profil;

        return $this;
    }

    public function getTarifs(): ?float
    {
        return $this->tarifs;
    }

    public function setTarifs(?float $tarifs): self
    {
        $this->tarifs = $tarifs;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTarifsPath(): ?string
    {
        return $this->tarifs_path;
    }

    public function setTarifsPath(?string $tarifs_path): self
    {
        $this->tarifs_path = $tarifs_path;

        return $this;
    }

    public function getChampsSupp(): ?string
    {
        return $this->champs_supp;
    }

    public function setChampsSupp(?string $champs_supp): self
    {
        $this->champs_supp = $champs_supp;

        return $this;
    }

    public function getHorraires(): ?string
    {
        return $this->horraires;
    }

    public function setHorraires(?string $horraires): self
    {
        $this->horraires = $horraires;

        return $this;
    }

    public function getPhoneFix(): ?string
    {
        return $this->phone_fix;
    }

    public function setPhoneFix(?string $phone_fix): self
    {
        $this->phone_fix = $phone_fix;

        return $this;
    }

    public function getPhoneMobile(): ?string
    {
        return $this->phone_mobile;
    }

    public function setPhoneMobile(?string $phone_mobile): self
    {
        $this->phone_mobile = $phone_mobile;

        return $this;
    }
}

src/Form/PartenaireType.php
<?php

namespace App\Form;

use App\Entity\Partenaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class PartenaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('specialite')
            ->add('adresse')
            ->add('ville')
            ->add('logo', FileType::class, [
                'label' => 'Fichier Tarifs (Xlsx, Word)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                        ],
                        'mimeTypesMessage' => 'Please upload a valid XLSX document',
                    ])
                ],
            ])
            ->add('entreprise')
            ->add('phone_mobile')
            ->add('phone_fix')
            ->add('champs_supp')
            ->add('description_profil')
            ->add('logo_path', FileType::class, [
                'label' => 'BDD prestataire (Xlsx, Word)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                        ],
                        'mimeTypesMessage' => 'Please upload a valid XLSX document',
                    ])
                ],
            ])
//            ->add('tarifs')
            ->add('user',UserType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Partenaire::class,
        ]);
    }
}

src/Controller/PartenaireController.php
<?php

namespace App\Controller;

use App\Entity\Partenaire;
use App\Entity\User;
use App\Form\PartenaireType;
use App\Repository\PartenaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/partenaire")
 */
class PartenaireController extends AbstractController
{
    /**
     * @Route("/", name="partenaire_index", methods={"GET"})
     */
    public function index(PartenaireRepository $partenaireRepository): Response
    {
        return $this->render('partenaire/index.html.twig', [
            'partenaires' => $partenaireRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="partenaire_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $partenaire = new Partenaire();
        $form = $this->createForm(PartenaireType::class, $partenaire);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $user = new User();
            $user->setUsername($partenaire->getUser()->getUsername());
            $user->setPassword(null);
            $user->setIsLocked(false);
            $user->setType("Partenaire");
            $user->setRole("ROLE_PARTENAIRE");
            $user->setCreatedTime(new \DateTime());
            $partenaire->setUser($user);

            /** @var UploadedFile $tarifsFile */
            $tarifsFile = $form->get('tarifs')->getData();
            if ($tarifsFile) {
                $originalFilename = pathinfo($tarifsFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$tarifsFile->guessExtension();
                try {
                    $tarifsFile->move(
                        $this->getParameter('upload_tarifs_partenaire'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    var_dump("erreur uploading file : ".$e->getMessage());
                }
                $partenaire->setLogo($newFilename);
            }


            /** @var UploadedFile $dbPrestatireFile */
            $dbPrestatireFile = $form->get('logo_path')->getData();
            if ($dbPrestatireFile) {
                $originalFilename = pathinfo($dbPrestatireFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$dbPrestatireFile->guessExtension();
                try {
                    $dbPrestatireFile->move(
                        $this->getParameter('upload_prestataire_partenaire'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    var_dump("erreur uploading file : ".$e->getMessage());
                }
                $partenaire->setLogoPath($newFilename);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($partenaire);
            $entityManager->flush();

            return $this->redirectToRoute('partenaire_index');
        }

        return $this->render('partenaire/new.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="partenaire_show", methods={"GET"})
     */
    public function show(Partenaire $partenaire): Response
    {
        return $this->render('partenaire/show.html.twig', [
            'partenaire' => $partenaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="partenaire_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Partenaire $partenaire): Response
    {
        $form = $this->createForm(PartenaireType::class, $partenaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('partenaire_index');
        }

        return $this->render('partenaire/edit.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="partenaire_delete", methods={"POST"})
     */
    public function delete(Request $request, Partenaire $partenaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$partenaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($partenaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('partenaire_index');
    }
}

templates/partenaire/_delete_form.html.twig
<form method="post" action="{{ path('partenaire_delete', {'id': partenaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ partenaire.id) }}">
    <button class="btn btn-danger btn-default">Delete</button>
</form>

templates/partenaire/_form.html.twig
{{ form_start(form) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

<div class="item form-group">
    {{ form_label(form.nom, 'Nom',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group has-feedback">
        {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
        <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
    </div>
    <small>{{ form_help(form.nom) }}</small>
</div>
<div class="item form-group">
    {{ form_label(form.prenom, 'Prenom',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group has-feedback">
        {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
        <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
    </div>
    <small>{{ form_help(form.prenom) }}</small>
</div>

    <div class="item form-group">
        {{ form_label(form.entreprise, 'Entreprise',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
        <div class="col-md-6 col-sm-6  form-group has-feedback">
            {{ form_widget(form.entreprise, {'attr': {'class': 'form-control'}}) }}
            <span class="fa fa-building form-control-feedback right" aria-hidden="true"></span>
        </div>
        <small>{{ form_help(form.entreprise) }}</small>
    </div>

<div class="item form-group">
    {{ form_label(form.specialite, 'Spécialité',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group has-feedback">
        {{ form_widget(form.specialite, {'attr': {'class': 'form-control'}}) }}
        <span class="fa fa-building form-control-feedback right" aria-hidden="true"></span>
    </div>
    <small>{{ form_help(form.specialite) }}</small>
</div>


<div class="item form-group">
    {{ form_label(form.adresse, 'adresse',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group has-feedback">
        {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
        <span class="fa fa-map-marker form-control-feedback right" aria-hidden="true"></span>
    </div>
    <small>{{ form_help(form.adresse) }}</small>
</div>


<div class="item form-group">
    {{ form_label(form.ville, 'Ville',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group has-feedback">
        {{ form_widget(form.ville, {'attr': {'class': 'form-control'}}) }}
        <span class="fa fa-map-pin form-control-feedback right" aria-hidden="true"></span>
    </div>
    <small>{{ form_help(form.ville) }}</small>
</div>

<div class="item form-group">
    {{ form_label(form.phone_mobile, 'Téléphone mobile',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group has-feedback">
        {{ form_widget(form.phone_mobile, {'attr': {'class': 'form-control'}}) }}
        <span class="fa fa-mobile-phone form-control-feedback right" aria-hidden="true"></span>
    </div>
    <small>{{ form_help(form.phone_mobile) }}</small>
</div>

<div class="item form-group">
    {{ form_label(form.phone_fix, 'Téléphone mobile',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group has-feedback">
        {{ form_widget(form.phone_fix, {'attr': {'class': 'form-control'}}) }}
        <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
    </div>
    <small>{{ form_help(form.phone_fix) }}</small>
</div>

<div class="item form-group">
    {{ form_label(form.logo_path, 'BDD prestataire',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    {{ form_widget(form.logo_path, {'attr': {'class': 'file'}}) }}
    <small>{{ form_help(form.logo_path) }}</small>
</div>

<div class="item form-group">
    {{ form_label(form.logo, 'Tarifs',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    {{ form_widget(form.logo, {'attr': {'class': 'file'}}) }}
    <small>{{ form_help(form.logo) }}</small>
</div>

<div class="item form-group">
    {{ form_label(form.champs_supp, 'Champs supplémentaire',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group ">
        {{ form_widget(form.champs_supp, {'attr': {'class': 'form-control'}}) }}
    </div>
    <small>{{ form_help(form.champs_supp) }}</small>
</div>

<div class="item form-group">
    {{ form_label(form.description_profil, 'Zone de Text',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group ">
        {{ form_widget(form.description_profil, {'attr': {'class': 'form-control'}}) }}
    </div>
    <small>{{ form_help(form.description_profil) }}</small>
</div>


<div class="item form-group">
    {{ form_label(form.user.email, 'Email',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group has-feedback">
        {{ form_widget(form.user.email, {'attr': {'class': 'form-control'}}) }}
        <span class="fa fa-envelope form-control-feedback right" aria-hidden="true"></span>
    </div>
    <small>{{ form_help(form.user.email) }}</small>
</div>

<div class="item form-group">
    {{ form_label(form.user.username, 'Nom d\'utilisateur',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
    <div class="col-md-6 col-sm-6  form-group">
        {{ form_widget(form.user.username, {'attr': {'class': 'form-control' }}) }}
    </div>
    <small>{{ form_help(form.user.username) }}</small>
</div>

<div class="ln_solid"></div>
<div class="item form-group">
    <div class="col-md-6 col-sm-6 offset-md-3">
        <button class="btn btn-primary" type="reset">Reset</button>
        <button class="btn btn-success">{{ button_label|default('Submit') }}</button>
    </div>
</div>
{{ form_end(form) }}

templates/partenaire/edit.html.twig
{% extends '/admin/index.html.twig' %}


{% block title_admin %}Edit Partenaire{% endblock %}


{% block content %}

    <h1>Edit Partenaire</h1>

    {{ include('partenaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('partenaire_index') }}">back to list</a>

    {{ include('partenaire/_delete_form.html.twig') }}
{% endblock %}

templates/partenaire/index.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Partenaire index{% endblock %}
{% block title_page_admin %}Espace Partenaire accès administrateur{% endblock %}


{% block content %}
<div class="x_panel">
    <div class="x_title">
        <h2>   Actions
        </h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>

    <div class="x_content">
        <a href="{{ path('partenaire_new') }}"  class="btn btn-app">
            <i class="fa fa-save"></i> Nouveau
        </a>

    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Liste des partenaires</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">

        <table id="datatable_partenaire" class="table table-striped table-bordered dataTable no-footer">

            <thead>
                <tr>
                    <th>#</th>
                    <th>Nom & Prénom</th>
                    <th>Specialite</th>
                    <th>Entreprise</th>
                    <th>Adresse</th>
                    <th>Ville</th>
                    <th>Description profil</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for partenaire in partenaires %}
                <tr>
                    <td>{{ partenaire.id }}</td>
                    <td>{{ partenaire.nom ~ ' ' ~partenaire.prenom}}</td>
                    <td>{{ partenaire.specialite }}</td>
                    <td>{{ partenaire.entreprise }}</td>
                    <td>{{ partenaire.ville }}</td>
                    <td>{{ partenaire.adresse }}</td>
                    <td>{{ partenaire.descriptionProfil }}</td>
                    <td>
                        <a href="{{ path('partenaire_show', {'id': partenaire.id}) }}"  class="btn btn-default">
                            <i class="fa fa-eye"></i> show
                        </a>
                        <a href="{{ path('partenaire_edit', {'id': partenaire.id}) }}"  class="btn btn-default">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/partenaire/new.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Adherant index{% endblock %}
{% block title_page_admin %}Espace Partenaire <small>accès administrateur</small>{% endblock %}

{% block content %}
<div class="x_panel">
    <div class="x_content">

        <a href="{{ path('partenaire_index') }}" class="btn btn-app">
            <i class="fa fa-list"></i> List
        </a>

        <a href="{{ path('partenaire_new') }}" class="btn btn-app">
            <i class="fa fa-save"></i> Nouveau
        </a>

    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Partenaire</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">    <h1>Create new Partenaire</h1>

    {{ include('partenaire/_form.html.twig') }}
    </div>
</div>
{% endblock %}

templates/partenaire/show.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Partenaire show{% endblock %}
{% block title_page_admin %}Espace Partenaire accès administrateur{% endblock %}


{% block content %}
<div class="x_panel">
    <div class="x_title">
        <h2>   Actions
        </h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>

    <div class="x_content">
        <a href="{{ path('partenaire_index') }}"  class="btn btn-app">
            <i class="fa fa-list"></i>back to list
        </a>

        <a href="{{ path('partenaire_new') }}"  class="btn btn-app">
            <i class="fa fa-save"></i> Nouveau
        </a>

        <a href="{{ path('partenaire_edit', {'id': partenaire.id}) }}"  class="btn btn-app">
            <i class="fa fa-edit"></i>edit
        </a>

        {{ include('partenaire/_delete_form.html.twig') }}

    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Partenaire - <small>{{ partenaire.user.username }}</small> </h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">

    <table class="table">
        <tbody>
            <tr>
                <th>Nom & Prénom</th>
                <td>{{ partenaire.nom ~ ' ' ~ partenaire.prenom }}</td>
            </tr>
            <tr>
                <th>Entreprise</th>
                <td>{{ partenaire.entreprise }}</td>
            </tr>
            <tr>
                <th>Specialite</th>
                <td>{{ partenaire.specialite }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ partenaire.adresse }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ partenaire.ville }}</td>
            </tr>
            <tr>
                <th>Description profil</th>
                <td>{{ partenaire.descriptionProfil }}</td>
            </tr>
            <tr>
                <th>Tarifs</th>
                <td>{{ partenaire.logo }}</td>
            </tr>
            <tr>
                <th>BDD Prestataire</th>
                <td>{{ partenaire.logoPath }}</td>
            </tr>


        </tbody>
    </table>
    </div>
</div>
{% endblock %}