src/Entity/Employeur.php
<?php

namespace App\Entity;

use App\Repository\EmployeurRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmployeurRepository::class)
 */
class Employeur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $database_employees;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo_path;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activity;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="employeurs",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $subscription_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $expiring_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $confirmed_password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $assurance_contract;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatabaseEmployees(): ?string
    {
        return $this->database_employees;
    }

    public function setDatabaseEmployees(?string $database_employees): self
    {
        $this->database_employees = $database_employees;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logo_path;
    }

    public function setLogoPath(?string $logo_path): self
    {
        $this->logo_path = $logo_path;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(?string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getActivity(): ?string
    {
        return $this->activity;
    }

    public function setActivity(?string $activity): self
    {
        $this->activity = $activity;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSubscriptionDate(): ?\DateTimeInterface
    {
        return $this->subscription_date;
    }

    public function setSubscriptionDate(?\DateTimeInterface $subscription_date): self
    {
        $this->subscription_date = $subscription_date;

        return $this;
    }

    public function getExpiringDate(): ?\DateTimeInterface
    {
        return $this->expiring_date;
    }

    public function setExpiringDate(?\DateTimeInterface $expiring_date): self
    {
        $this->expiring_date = $expiring_date;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getConfirmedPassword(): ?string
    {
        return $this->confirmed_password;
    }

    public function setConfirmedPassword(?string $confirmed_password): self
    {
        $this->confirmed_password = $confirmed_password;

        return $this;
    }

    public function getAssuranceContract(): ?string
    {
        return $this->assurance_contract;
    }

    public function setAssuranceContract(?string $assurance_contract): self
    {
        $this->assurance_contract = $assurance_contract;

        return $this;
    }


    /**
     * Generates the magic method
     *
     */
    public function __toString(): ?string
    {
        // to show the name of the Category in the select
        return $this->id;
    }
}

src/Form/EmployeurType.php
<?php

namespace App\Form;

use App\Entity\Employeur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class EmployeurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('database_employees', FileType::class, [
                'label' => 'Fichier employees (Xlsx, Word)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                        ],
                        'mimeTypesMessage' => 'Please upload a valid XLSX document',
                    ])
                ],
            ])
            ->add('entreprise')
            ->add('activity')
//            ->add('subscription_date')
//            ->add('expiring_date')
//            ->add('password')
//            ->add('confirmed_password')
            ->add('logo', FileType::class, [
                'label' => 'Logo (Image)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF document',
                    ])
                ],
            ])
            ->add('user',UserType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Employeur::class,
        ]);
    }
}

src/Controller/EmployeurController.php
<?php

namespace App\Controller;

use App\Entity\Employeur;
use App\Entity\User;
use App\Form\EmployeurType;
use App\Repository\EmployeurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/employeur")
 */
class EmployeurController extends AbstractController
{
    /**
     * @Route("/", name="employeur_index", methods={"GET"})
     */
    public function index(EmployeurRepository $employeurRepository): Response
    {
        return $this->render('employeur/index.html.twig', [
            'employeurs' => $employeurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="employeur_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $employeur = new Employeur();
        $form = $this->createForm(EmployeurType::class, $employeur);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $user = new User();
            $user->setUsername($employeur->getUser()->getUsername());
            $user->setPassword($employeur->getPassword());
            $user->setIsLocked(false);
            $user->setType("Employeur");
            $user->setRole("ROLE_EMPLOYEUR");
            $user->setCreatedTime(new \DateTime());
            $employeur->setUser($user);

            /** @var UploadedFile $logoFile */
            $logoFile = $form->get('logo')->getData();
            // this condition is needed because the  field is not required
            // so the  file must be processed only when a file is uploaded
            if ($logoFile) {
                $originalFilename = pathinfo($logoFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$logoFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $logoFile->move(
                        $this->getParameter('upload_logo_employeur'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    var_dump("erreur uploading file : ".$e->getMessage());
                    // ... handle exception if something happens during file upload
                }

                // updates the '$newFilename' property to store the  file name
                // instead of its contents
                $employeur->setLogo($newFilename);
            }


            /** @var UploadedFile $dbEmployeurFile */
            $dbEmployeurFile = $form->get('database_employees')->getData();
            if ($dbEmployeurFile) {
                $originalFilename = pathinfo($dbEmployeurFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$dbEmployeurFile->guessExtension();

                try {
                    $dbEmployeurFile->move(
                        $this->getParameter('upload_fichieremployeur_employeur'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    var_dump("erreur uploading file : ".$e->getMessage());
                }
                $employeur->setDatabaseEmployees($newFilename);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($employeur);
            $entityManager->flush();

            return $this->redirectToRoute('employeur_index');
        }

        return $this->render('employeur/new.html.twig', [
            'employeur' => $employeur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="employeur_show", methods={"GET"})
     */
    public function show(Employeur $employeur): Response
    {
        return $this->render('employeur/show.html.twig', [
            'employeur' => $employeur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="employeur_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Employeur $employeur): Response
    {
        $form = $this->createForm(EmployeurType::class, $employeur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('employeur_index');
        }

        return $this->render('employeur/edit.html.twig', [
            'employeur' => $employeur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="employeur_delete", methods={"POST"})
     */
    public function delete(Request $request, Employeur $employeur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employeur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($employeur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('employeur_index');
    }
}

templates/employeur/_delete_form.html.twig
<form method="post" action="{{ path('employeur_delete', {'id': employeur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employeur.id) }}">
    <button class="btn btn-danger btn-default">Delete</button>
</form>

templates/employeur/_form.html.twig
<br/>
{{ form_start(form) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <div class="item form-group">
        {{ form_label(form.entreprise, 'Entreprise',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
        <div class="col-md-6 col-sm-6  form-group has-feedback">
            {{ form_widget(form.entreprise, {'attr': {'class': 'form-control'}}) }}
            <span class="fa fa-building form-control-feedback right" aria-hidden="true"></span>
        </div>
        <small>{{ form_help(form.entreprise) }}</small>
    </div>

    <div class="item form-group">
        {{ form_label(form.activity, 'Activité',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
        <div class="col-md-6 col-sm-6  form-group has-feedback">
            {{ form_widget(form.activity, {'attr': {'class': 'form-control'}}) }}
            <span class="fa fa-building form-control-feedback right" aria-hidden="true"></span>
        </div>
        <small>{{ form_help(form.activity) }}</small>
    </div>

    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align">Date d'inscription</label>
        <div class="col-md-6 col-sm-6  form-group has-feedback">
            <input name="employeur[subscription_date]" class="date-picker form-control" type="date" value="{{ employeur.subscriptiondate | date }}">
        </div>
    </div>

    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align">Date d'expiration</label>
        <div class="col-md-6 col-sm-6  form-group has-feedback">
            <input name="employeur[expiring_date]" class="date-picker form-control" type="date" value="{{ employeur.expiringdate | date }}">
        </div>
    </div>

    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align">Mot de passe</label>
        <div class="col-md-6 col-sm-6  form-group">
            <input name="employeur[password]" class="form-control" type="password" value="{{ employeur.password }}">
        </div>
    </div>

    <div class="item form-group">
        <label class="col-form-label col-md-3 col-sm-3 label-align">Confirmer le mot de passe</label>
        <div class="col-md-6 col-sm-6  form-group">
            <input name="employeur[confirmed_password]" class="form-control" type="password" value="{{ employeur.confirmedpassword }}">
        </div>
    </div>

    <div class="item form-group">
        {{ form_label(form.database_employees, 'Fichier employés',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
        {{ form_widget(form.database_employees, {'attr': {'class': 'file'}}) }}
        <small>{{ form_help(form.database_employees) }}</small>
    </div>

    <div class="item form-group">
        {{ form_label(form.logo, 'Logo',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
        {{ form_widget(form.logo, {'attr': {'class': 'file'}}) }}
        <small>{{ form_help(form.logo) }}</small>
    </div>

    <div class="item form-group">
        {{ form_label(form.user.email, 'Email',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
        <div class="col-md-6 col-sm-6  form-group has-feedback">
            {{ form_widget(form.user.email, {'attr': {'class': 'form-control'}}) }}
            <span class="fa fa-envelope form-control-feedback right" aria-hidden="true"></span>
        </div>
        <small>{{ form_help(form.user.email) }}</small>
    </div>

    <div class="item form-group">
        {{ form_label(form.user.username, 'Nom d\'utilisateur',{label_attr: {class: 'col-form-label col-md-3 col-sm-3 label-align'}} ) }}
        <div class="col-md-6 col-sm-6  form-group">
            {{ form_widget(form.user.username, {'attr': {'class': 'form-control' }}) }}
        </div>
        <small>{{ form_help(form.user.username) }}</small>
    </div>

    <div class="ln_solid"></div>
    <div class="item form-group">
        <div class="col-md-6 col-sm-6 offset-md-3">
            <button class="btn btn-primary" type="reset">Reset</button>
            <button class="btn btn-success">{{ button_label|default('Submit') }}</button>
        </div>
    </div>

{{ form_end(form) }}

templates/employeur/edit.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Employeur - edit{% endblock %}
{% block title_page_admin %}Espace Employeur <small>accès administrateur</small>{% endblock %}

{% block content %}
<div class="x_panel">
    <div class="x_content">

        <a href="{{ path('employeur_index') }}" class="btn btn-app">
            <i class="fa fa-list"></i> List
        </a>

        <a href="{{ path('employeur_new') }}" class="btn btn-app">
            <i class="fa fa-save"></i> Nouveau
        </a>

        {{ include('employeur/_delete_form.html.twig') }}

    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Employeur</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
    {{ include('employeur/_form.html.twig', {'button_label': 'Update'}) }}

    </div>
</div>
{% endblock %}

templates/employeur/index.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Employeur index{% endblock %}
{% block title_page_admin %}Espace Employeur accès administrateur{% endblock %}


{% block content %}
<div class="x_panel">
    <div class="x_title">
        <h2>   Actions
        </h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>

    <div class="x_content">
        <a href="{{ path('employeur_new') }}"  class="btn btn-app">
            <i class="fa fa-save"></i> Nouveau
        </a>

    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Liste des employeurs</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">

        <table id="datatable_employeur" class="table table-striped table-bordered dataTable no-footer">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Entreprise</th>
                    <th>Activity</th>
                    <th>Date d'inscription</th>
                    <th>Date d'expiration</th>
                    <th>logo</th>
                    <th>DB employeurs</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
                {% for employeur in employeurs %}
                <tr>
                    <td>{{ employeur.id }}</td>
                    <td>{{ employeur.entreprise }}</td>
                    <td>{{ employeur.activity }}</td>
                    <td>{{ employeur.subscriptiondate | date }}</td>
                    <td>{{ employeur.expiringdate | date }}</td>
                    <td><img src="{{  asset('/uploads/employeur/logos/'~employeur.logo) }}" width="45px" height="45px"/> </td>
                    <td><a href="{{  asset('/uploads/employeur/fichiers_employeur/'~employeur.databaseemployees) }}" >
                            <i class="fa fa-download"></i>Télécharger le base</a> </td>
                    <td>
                        <a href="{{ path('employeur_show', {'id': employeur.id}) }}"  class="btn btn-default">
                            <i class="fa fa-eye"></i> show
                        </a>
                        <a href="{{ path('employeur_edit', {'id': employeur.id}) }}"  class="btn btn-default">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block extra_script_admin %}
{% endblock %}

templates/employeur/new.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Adherant index{% endblock %}
{% block title_page_admin %}Espace Employeur <small>accès administrateur</small>{% endblock %}

{% block content %}
<div class="x_panel">
    <div class="x_content">

        <a href="{{ path('employeur_index') }}" class="btn btn-app">
            <i class="fa fa-list"></i> List
        </a>

        <a href="{{ path('employeur_new') }}" class="btn btn-app">
            <i class="fa fa-save"></i> Nouveau
        </a>

    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Employeur</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">

        {{ include('employeur/_form.html.twig') }}

    </div>
</div>
{% endblock %}

templates/employeur/show.html.twig
{% extends '/admin/index.html.twig' %}

{% block title_admin %}Show Employeur{% endblock %}

{% block content %}

    <h1>Employeur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ employeur.id }}</td>
            </tr>
            <tr>
                <th>Database_employees</th>
                <td>{{ employeur.databaseEmployees }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ employeur.logo }}</td>
            </tr>
            <tr>
                <th>Logo_path</th>
                <td>{{ employeur.logoPath }}</td>
            </tr>
            <tr>
                <th>Entreprise</th>
                <td>{{ employeur.entreprise }}</td>
            </tr>
            <tr>
                <th>Activity</th>
                <td>{{ employeur.activity }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('employeur_index') }}">back to list</a>

    <a href="{{ path('employeur_edit', {'id': employeur.id}) }}">edit</a>

    {{ include('employeur/_delete_form.html.twig') }}
{% endblock %}