src/Entity/Adherant.php
<?php

namespace App\Entity;

use App\Repository\AdherantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdherantRepository::class)
 */
class Adherant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_soinclair;

    /**
    * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cartesoinclair;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $cin;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="adherants",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_client;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_conjoint_first;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_conjoint_second;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbr_enfant;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $situation_pro;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $category_sociopro;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $maladie_chroni;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $formule_soin_clair;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $supp_one;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $supp_two;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $supp_three;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phonenumber;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $subscription_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $expiring_date;

    /**
     * @ORM\OneToMany(targetEntity=Demande::class, mappedBy="adherent", orphanRemoval=true)
     */
    private $demandes;

    public function __construct()
    {
        $this->demandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCartesoinclair(): ?string {
        return $this->cartesoinclair;
    }

    public function setCartesoinclair(string $cartesoinclair): self{
        $this->cartesoinclair = $cartesoinclair;
        return $this;
    }

    public function getNumeroSoinclair(): ?string
    {
        return $this->numero_soinclair;
    }

    public function setNumeroSoinclair(string $numero_soinclair): self
    {
        $this->numero_soinclair = $numero_soinclair;

        return $this;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(string $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(?string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getCodeClient(): ?string
    {
        return $this->code_client;
    }

    public function setCodeClient(?string $code_client): self
    {
        $this->code_client = $code_client;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getNomConjointFirst(): ?string
    {
        return $this->nom_conjoint_first;
    }

    public function setNomConjointFirst(?string $nom_conjoint_first): self
    {
        $this->nom_conjoint_first = $nom_conjoint_first;

        return $this;
    }

    public function getNomConjointSecond(): ?string
    {
        return $this->nom_conjoint_second;
    }

    public function setNomConjointSecond(?string $nom_conjoint_second): self
    {
        $this->nom_conjoint_second = $nom_conjoint_second;

        return $this;
    }

    public function getNbrEnfant(): ?int
    {
        return $this->nbr_enfant;
    }

    public function setNbrEnfant(?int $nbr_enfant): self
    {
        $this->nbr_enfant = $nbr_enfant;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getSituationPro(): ?string
    {
        return $this->situation_pro;
    }

    public function setSituationPro(string $situation_pro): self
    {
        $this->situation_pro = $situation_pro;

        return $this;
    }

    public function getCategorySociopro(): ?string
    {
        return $this->category_sociopro;
    }

    public function setCategorySociopro(?string $category_sociopro): self
    {
        $this->category_sociopro = $category_sociopro;

        return $this;
    }

    public function getMaladieChroni(): ?string
    {
        return $this->maladie_chroni;
    }

    public function setMaladieChroni(?string $maladie_chroni): self
    {
        $this->maladie_chroni = $maladie_chroni;

        return $this;
    }

    public function getFormuleSoinClair(): ?string
    {
        return $this->formule_soin_clair;
    }

    public function setFormuleSoinClair(?string $formule_soin_clair): self
    {
        $this->formule_soin_clair = $formule_soin_clair;

        return $this;
    }

    public function getSuppOne(): ?string
    {
        return $this->supp_one;
    }

    public function setSuppOne(?string $supp_one): self
    {
        $this->supp_one = $supp_one;

        return $this;
    }

    public function getSuppTwo(): ?string
    {
        return $this->supp_two;
    }

    public function setSuppTwo(?string $supp_two): self
    {
        $this->supp_two = $supp_two;

        return $this;
    }

    public function getSuppThree(): ?string
    {
        return $this->supp_three;
    }

    public function setSuppThree(?string $supp_three): self
    {
        $this->supp_three = $supp_three;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPhonenumber(): ?string
    {
        return $this->phonenumber;
    }

    public function setPhonenumber(?string $phonenumber): self
    {
        $this->phonenumber = $phonenumber;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getSubscriptionDate(): ?\DateTimeInterface
    {
        return $this->subscription_date;
    }

    public function setSubscriptionDate(?\DateTimeInterface $subscription_date): self
    {
        $this->subscription_date = $subscription_date;

        return $this;
    }

    public function getExpiringDate(): ?\DateTimeInterface
    {
        return $this->expiring_date;
    }

    public function setExpiringDate(?\DateTimeInterface $expiring_date): self
    {
        $this->expiring_date = $expiring_date;

        return $this;
    }

    /**
     * @return Collection|Demande[]
     */
    public function getDemandes(): Collection
    {
        return $this->demandes;
    }

    public function addDemande(Demande $demande): self
    {
        if (!$this->demandes->contains($demande)) {
            $this->demandes[] = $demande;
            $demande->setAdherent($this);
        }

        return $this;
    }

    public function removeDemande(Demande $demande): self
    {
        if ($this->demandes->removeElement($demande)) {
            // set the owning side to null (unless already changed)
            if ($demande->getAdherent() === $this) {
                $demande->setAdherent(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $username;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $created_time;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $modified_time;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_locked;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $salt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity=Adherant::class, mappedBy="user")
     */
    private $adherants;

    /**
     * @ORM\OneToMany(targetEntity=Employeur::class, mappedBy="user")
     */
    private $employeurs;

    /**
     * @ORM\OneToMany(targetEntity=Partenaire::class, mappedBy="user")
     */
    private $partenaires;

    public function __construct()
    {
        $this->adherants = new ArrayCollection();
        $this->employeurs = new ArrayCollection();
        $this->partenaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getCreatedTime(): ?\DateTimeInterface
    {
        return $this->created_time;
    }

    public function setCreatedTime(?\DateTimeInterface $created_time): self
    {
        $this->created_time = $created_time;

        return $this;
    }

    public function getModifiedTime(): ?\DateTimeInterface
    {
        return $this->modified_time;
    }

    public function setModifiedTime(?\DateTimeInterface $modified_time): self
    {
        $this->modified_time = $modified_time;

        return $this;
    }

    public function getIsLocked(): ?bool
    {
        return $this->is_locked;
    }

    public function setIsLocked(bool $is_locked): self
    {
        $this->is_locked = $is_locked;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password = null): self
    {
        if($password == null || empty($password)){
            $this->password = $this->randomPassword();
        }else {
            $this->password = $password;
        }
        return $this;
    }

    public function getSalt(): ?string
    {
        return $this->salt;
    }

    public function setSalt(?string $salt): self
    {
        $this->salt = $salt;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }


    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(?string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return array($this->getRole());
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Adherant[]
     */
    public function getAdherants(): Collection
    {
        return $this->adherants;
    }

    public function addAdherant(Adherant $adherant): self
    {
        if (!$this->adherants->contains($adherant)) {
            $this->adherants[] = $adherant;
            $adherant->setUser($this);
        }

        return $this;
    }

    public function removeAdherant(Adherant $adherant): self
    {
        if ($this->adherants->removeElement($adherant)) {
            // set the owning side to null (unless already changed)
            if ($adherant->getUser() === $this) {
                $adherant->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Employeur[]
     */
    public function getEmployeurs(): Collection
    {
        return $this->employeurs;
    }

    public function addEmployeur(Employeur $employeur): self
    {
        if (!$this->employeurs->contains($employeur)) {
            $this->employeurs[] = $employeur;
            $employeur->setUser($this);
        }

        return $this;
    }

    public function removeEmployeur(Employeur $employeur): self
    {
        if ($this->employeurs->removeElement($employeur)) {
            // set the owning side to null (unless already changed)
            if ($employeur->getUser() === $this) {
                $employeur->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Partenaire[]
     */
    public function getPartenaires(): Collection
    {
        return $this->partenaires;
    }

    public function addPartenaire(Partenaire $partenaire): self
    {
        if (!$this->partenaires->contains($partenaire)) {
            $this->partenaires[] = $partenaire;
            $partenaire->setUser($this);
        }

        return $this;
    }

    public function removePartenaire(Partenaire $partenaire): self
    {
        if ($this->partenaires->removeElement($partenaire)) {
            // set the owning side to null (unless already changed)
            if ($partenaire->getUser() === $this) {
                $partenaire->setUser(null);
            }
        }

        return $this;
    }

    //render random password
    function randomPassword() {
        $alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';
        $pass = array(); //remember to declare $pass as an array
        $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
        for ($i = 0; $i < 8; $i++) {
            $n = rand(0, $alphaLength);
            $pass[] = $alphabet[$n];
        }
        return implode($pass); //turn the array into a string
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block content %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block content %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Firstname</th>
                <th>Phonenumber</th>
                <th>Created_time</th>
                <th>Modified_time</th>
                <th>Is_locked</th>
                <th>Password</th>
                <th>Salt</th>
                <th>Ville</th>
                <th>Email</th>
                <th>Subscription_date</th>
                <th>Expiring_date</th>
                <th>Role</th>
                <th>Type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.phonenumber }}</td>
                <td>{{ user.createdTime ? user.createdTime|date('Y-m-d') : '' }}</td>
                <td>{{ user.modifiedTime ? user.modifiedTime|date('Y-m-d') : '' }}</td>
                <td>{{ user.isLocked ? 'Yes' : 'No' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.salt }}</td>
                <td>{{ user.ville }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.subscriptionDate ? user.subscriptionDate|date('Y-m-d') : '' }}</td>
                <td>{{ user.expiringDate ? user.expiringDate|date('Y-m-d') : '' }}</td>
                <td>{{ user.role }}</td>
                <td>{{ user.type }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="16">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block content %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block content %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ user.firstname }}</td>
            </tr>
            <tr>
                <th>Phonenumber</th>
                <td>{{ user.phonenumber }}</td>
            </tr>
            <tr>
                <th>Created_time</th>
                <td>{{ user.createdTime ? user.createdTime|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Modified_time</th>
                <td>{{ user.modifiedTime ? user.modifiedTime|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Is_locked</th>
                <td>{{ user.isLocked ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Salt</th>
                <td>{{ user.salt }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ user.ville }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Subscription_date</th>
                <td>{{ user.subscriptionDate ? user.subscriptionDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Expiring_date</th>
                <td>{{ user.expiringDate ? user.expiringDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ user.role }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ user.type }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}